name: vuln

permissions: {} # no need any permissions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
  - cron: '0 10 * * 1' # run "At 10:00 on Monday"
  workflow_call:

jobs:
  run:
    name: vuln
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true

      - name: go version
        run: go version

      - name: install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: run govulncheck
        run: govulncheck -test ./...
